# Use root/example as user/password credentials
version: '3.1'

services:
  Tileserver:
    image: maptiler/tileserver-gl
    restart: always
    ports:
      - "127.0.0.1:9999:8080"
    volumes:
      -  ./tiles/:/data
