# Use root/example as user/password credentials
version: '3.1'

services:
  MittweidaTiles:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: mittweida
    ports:
      - "127.0.0.1:27017:27017"
